### ISSUE TITLE
Could you provide a version (please) that's compatible with node out of the box?

### ISSUE THREAD

**Issue by tandrewnichols** [kaelzhang/promise-faker#1]
At one point, I had this lib working in our node tests, but only by specifically requiring `promise-faker/src`. Then I reinstalled node modules (so this dependency must've been updated) and now promise-faker/src/index is import/export based, but lib/index requires babel-runtime which is not listed under dependencies, so that fails too. Please, please, please . . . make node a first class citizen. If you then want to compile to something else for the browser, that's fine.

**Comment by tandrewnichols** [comment]
I.e. requiring lib/index gives me:

```
Error: Cannot find module 'babel-runtime/core-js/object/define-property'
```

but requiring src/index gives me:

```
Message:
     SyntaxError: Unexpected token import
   Stacktrace:
     /Users/AndrewNichols/code/anichols/manta/manta-frontend/node_modules/promise-faker/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import {
```

**Comment by tandrewnichols** [comment]
I was using 1.2.2 previously, so it seems like 1.2.3 was not actually a patch change, as it breaks backward compatibility.

**Comment by kaelzhang** [comment]
Sorry for that. Fixed and landed in `1.2.5`. `1.2.3` is not a breaking change but a bug version. 

The `/src` directory intends to be used by bundlers, such as rollup or webpack, as the main entry of es6 modules. So it is better not to `require` the directory directly.

**Comment by tandrewnichols** [comment]
Thanks for the fast fix! I'll try it out tomorrow.

**Comment by kaelzhang** [comment]
If there are any issues, plz bug me 🤝

**Comment by tandrewnichols** [comment]
Forgot to respond. It's working great. Thanks again!
